export const LOAD_DEMAND_FARES_BY_BRANCH =
  'DemandFareTimeLineByBranch/LOAD_DEMAND_FARES_BY_BRANCH';
export const LOAD_DEMAND_FARES_BY_BRANCH_SUCCESS =
  'DemandFareTimeLineByBranch/LOAD_DEMAND_FARES_BY_BRANCH_SUCCESS';
export const LOAD_DEMAND_FARES_BY_BRANCH_ERROR =
  'DemandFareTimeLineByBranch/LOAD_DEMAND_FARES_BY_BRANCH_ERROR';
