export const LOAD_MY_PERFORMANCE_INDEXS =
  'MyPerformanceIndexPage/LOAD_MY_PERFORMANCE_INDEXS';
export const LOAD_MY_PERFORMANCE_INDEXS_SUCCESS =
  'MyPerformanceIndexPage/LOAD_MY_PERFORMANCE_INDEXS_SUCCESS';
export const LOAD_MY_PERFORMANCE_INDEXS_ERROR =
  'MyPerformanceIndexPage/LOAD_MY_PERFORMANCE_INDEXS_ERROR';

export const REMOVE_MY_PERFORMANCE_INDEX =
  'MyPerformanceIndexPage/REMOVE_MY_PERFORMANCE_INDEX';
export const REMOVE_MY_PERFORMANCE_INDEX_SUCCESS =
  'MyPerformanceIndexPage/REMOVE_MY_PERFORMANCE_INDEX_SUCCESS';
export const REMOVE_MY_PERFORMANCE_INDEX_ERROR =
  'MyPerformanceIndexPage/REMOVE_MY_PERFORMANCE_INDEX_ERROR';

export const CREATE_MY_PERFORMANCE_INDEX =
  'MyPerformanceIndexPage/CREATE_MY_PERFORMANCE_INDEX';
export const CREATE_MY_PERFORMANCE_INDEX_ERROR =
  'MyPerformanceIndexPage/CREATE_MY_PERFORMANCE_INDEX_ERROR';
export const CREATE_MY_PERFORMANCE_INDEX_SUCCESS =
  'MyPerformanceIndexPage/CREATE_MY_PERFORMANCE_INDEX_SUCCESS';

export const EDIT_MY_PERFORMANCE_INDEX =
  'MyPerformanceIndexPage/EDIT_MY_PERFORMANCE_INDEX';
export const EDIT_MY_PERFORMANCE_INDEX_ERROR =
  'MyPerformanceIndexPage/EDIT_MY_PERFORMANCE_INDEX_ERROR';
export const EDIT_MY_PERFORMANCE_INDEX_SUCCESS =
  'MyPerformanceIndexPage/EDIT_MY_PERFORMANCE_INDEX_SUCCESS';
