export const LOAD_USER_MAIL_AUTO_COMPLETES =
  'UserMailAutoCompleteSelect/LOAD_USER_MAIL_AUTO_COMPLETES';
export const LOAD_USER_MAIL_AUTO_COMPLETES_SUCCESS =
  'UserMailAutoCompleteSelect/LOAD_USER_MAIL_AUTO_COMPLETES_SUCCESS';
export const LOAD_USER_MAIL_AUTO_COMPLETES_ERROR =
  'UserMailAutoCompleteSelect/LOAD_USER_MAIL_AUTO_COMPLETES_ERROR';
