export const LOAD_DEMAND_FARE_BY_ID = 'DemandFare/LOAD_DEMAND_FARE_BY_ID';
export const LOAD_DEMAND_FARE_BY_ID_ERROR =
  'DemandFare/LOAD_DEMAND_FARE_BY_ID_ERROR';
export const LOAD_DEMAND_FARE_BY_ID_SUCCESS =
  'DemandFare/LOAD_DEMAND_FARE_BY_ID_SUCCESS';
