export const EDIT_DISABLE_DEMAND_EXCEED_FARE =
  'DisableFareForm/EDIT_DISABLE_DEMAND_EXCEED_FARE';
export const EDIT_DISABLE_DEMAND_EXCEED_FARE_ERROR =
  'DisableFareForm/EDIT_DISABLE_DEMAND_EXCEED_FARE_ERROR';
export const EDIT_DISABLE_DEMAND_EXCEED_FARE_SUCCESS =
  'DisableFareForm/EDIT_DISABLE_DEMAND_EXCEED_FARE_SUCCESS';
