export const REMOVE_GROUPING = 'GroupingForm/REMOVE_GROUPING';
export const REMOVE_GROUPING_SUCCESS = 'GroupingForm/REMOVE_GROUPING_SUCCESS';
export const REMOVE_GROUPING_ERROR = 'GroupingForm/REMOVE_GROUPING_ERROR';

export const CREATE_GROUPING = 'GroupingForm/CREATE_GROUPING';
export const CREATE_GROUPING_ERROR = 'GroupingForm/CREATE_GROUPING_ERROR';
export const CREATE_GROUPING_SUCCESS = 'GroupingForm/CREATE_GROUPING_SUCCESS';

export const EDIT_GROUPING = 'GroupingForm/EDIT_GROUPING';
export const EDIT_GROUPING_ERROR = 'GroupingForm/EDIT_GROUPING_ERROR';
export const EDIT_GROUPING_SUCCESS = 'GroupingForm/EDIT_GROUPING_SUCCESS';
