export const LOAD_ALERT_CONFIGURATIONS =
  'AlertConfiguration/LOAD_ALERT_CONFIGURATIONS';
export const LOAD_ALERT_CONFIGURATIONS_SUCCESS =
  'AlertConfiguration/LOAD_ALERT_CONFIGURATIONS_SUCCESS';
export const LOAD_ALERT_CONFIGURATIONS_ERROR =
  'AlertConfiguration/LOAD_ALERT_CONFIGURATIONS_ERROR';
