export const LOAD_CONSUMPTIONS = 'App/ConsumptionPage/LOAD_CONSUMPTIONS';
export const LOAD_CONSUMPTIONS_SUCCESS =
  'App/ConsumptionPage/LOAD_CONSUMPTIONS_SUCCESS';
export const LOAD_CONSUMPTIONS_ERROR =
  'App/ConsumptionPage/LOAD_CONSUMPTIONS_ERROR';
export const CONSUMPTIONS_ERRORS = 'App/ConsumptionPage/CONSUMPTIONS_ERRORS';
export const CONSUMPTIONS_FARE_AND_WORKING_HOURS_ERRORS =
  'App/ConsumptionPage/CONSUMPTIONS_FARE_AND_WORKING_HOURS_ERRORS';
