export const EDIT_DISABLE_DEMAND_FARE =
  'DisableDemandFareForm/EDIT_DISABLE_DEMAND_FARE';
export const EDIT_DISABLE_DEMAND_FARE_ERROR =
  'DisableDemandFareForm/EDIT_DISABLE_DEMAND_FARE_ERROR';
export const EDIT_DISABLE_DEMAND_FARE_SUCCESS =
  'DisableDemandFareForm/EDIT_DISABLE_DEMAND_FARE_SUCCESS';
