export const REMOVE_DEMAND_EXCEED_FARE =
  'DemandExceedFareForm/REMOVE_DEMAND_EXCEED_FARE';
export const REMOVE_DEMAND_EXCEED_FARE_SUCCESS =
  'DemandExceedFareForm/REMOVE_DEMAND_EXCEED_FARE_SUCCESS';
export const REMOVE_DEMAND_EXCEED_FARE_ERROR =
  'DemandExceedFareForm/REMOVE_DEMAND_EXCEED_FARE_ERROR';

export const CREATE_DEMAND_EXCEED_FARE =
  'DemandExceedFareForm/CREATE_DEMAND_EXCEED_FARE';
export const CREATE_DEMAND_EXCEED_FARE_ERROR =
  'DemandExceedFareForm/CREATE_DEMAND_EXCEED_FARE_ERROR';
export const CREATE_DEMAND_EXCEED_FARE_SUCCESS =
  'DemandExceedFareForm/CREATE_DEMAND_EXCEED_FARE_SUCCESS';

export const EDIT_DEMAND_EXCEED_FARE =
  'DemandExceedFareForm/EDIT_DEMAND_EXCEED_FARE';
export const EDIT_DEMAND_EXCEED_FARE_ERROR =
  'DemandExceedFareForm/EDIT_DEMAND_EXCEED_FARE_ERROR';
export const EDIT_DEMAND_EXCEED_FARE_SUCCESS =
  'DemandExceedFareForm/EDIT_DEMAND_EXCEED_FARE_SUCCESS';
