export const BRANCH_CONSUMPTION_FARE_NOT_FOUND =
  'BRANCH_CONSUMPTION_FARE_NOT_FOUND';
export const BRANCH_WORKING_HOUR_NOT_FOUND = 'BRANCH_WORKING_HOUR_NOT_FOUND';
export const EGG_WORKING_HOUR_NOT_FOUND = 'EGG_WORKING_HOUR_NOT_FOUND';
