export const LOAD_DASHBOARD = 'Dashboard/LOAD_DASHBOARD';
export const LOAD_DASHBOARD_SUCCESS = 'Dashboard/LOAD_DASHBOARD_SUCCESS';
export const LOAD_DASHBOARD_ERROR = 'Dashboard/LOAD_DASHBOARD_ERROR';

export const LOAD_DASHBOARD_REAL_TIME = 'Dashboard/LOAD_DASHBOARD_REAL_TIME';
export const LOAD_DASHBOARD_REAL_TIME_SUCCESS =
  'Dashboard/LOAD_DASHBOARD_REAL_TIME_SUCCESS';
export const LOAD_DASHBOARD_REAL_TIME_ERROR =
  'Dashboard/LOAD_DASHBOARD_REAL_TIME_ERROR';
export const STOP_DASHBOARD_REAL_TIME = 'Dashboard/STOP_DASHBOARD_REAL_TIME';
export const STOP_DASHBOARD_REAL_TIME_SUCCESS =
  'Dashboard/STOP_DASHBOARD_REAL_TIME_SUCCESSS';
