export const LOAD_COMPANIES = 'Company/LOAD_COMPANIES';
export const LOAD_COMPANIES_SUCCESS = 'Company/LOAD_COMPANIES_SUCCESS';
export const LOAD_COMPANIES_ERROR = 'Company/LOAD_COMPANIES_ERROR';
export const SELECT_COMPANY = 'Company/SELECT_COMPANY';
