export const LOAD_KPI_REPORT_DATES = 'KpiReportDate/LOAD_KPI_REPORT_DATES';
export const LOAD_KPI_REPORT_DATES_SUCCESS =
  'KpiReportDate/LOAD_KPI_REPORT_DATES_SUCCESS';
export const LOAD_KPI_REPORT_DATES_ERROR =
  'KpiReportDate/LOAD_KPI_REPORT_DATES_ERROR';
