export const LOAD_CONSUMPTION_FARES_BY_BRANCH =
  'ConsumptionFareByBranch/LOAD_CONSUMPTION_FARES_BY_BRANCH';
export const LOAD_CONSUMPTION_FARES_BY_BRANCH_SUCCESS =
  'ConsumptionFareByBranch/LOAD_CONSUMPTION_FARES_BY_BRANCH_SUCCESS';
export const LOAD_CONSUMPTION_FARES_BY_BRANCH_ERROR =
  'ConsumptionFareByBranch/LOAD_CONSUMPTION_FARES_BY_BRANCH_ERROR';
