export const REMOVE_FILL_KPI_REPORT =
  'FillKpiReportForm/REMOVE_FILL_KPI_REPORT';
export const REMOVE_FILL_KPI_REPORT_SUCCESS =
  'FillKpiReportForm/REMOVE_FILL_KPI_REPORT_SUCCESS';
export const REMOVE_FILL_KPI_REPORT_ERROR =
  'FillKpiReportForm/REMOVE_FILL_KPI_REPORT_ERROR';

export const CREATE_FILL_KPI_REPORT =
  'FillKpiReportForm/CREATE_FILL_KPI_REPORT';
export const CREATE_FILL_KPI_REPORT_ERROR =
  'FillKpiReportForm/CREATE_FILL_KPI_REPORT_ERROR';
export const CREATE_FILL_KPI_REPORT_SUCCESS =
  'FillKpiReportForm/CREATE_FILL_KPI_REPORT_SUCCESS';

export const EDIT_FILL_KPI_REPORT = 'FillKpiReportForm/EDIT_FILL_KPI_REPORT';
export const EDIT_FILL_KPI_REPORT_ERROR =
  'FillKpiReportForm/EDIT_FILL_KPI_REPORT_ERROR';
export const EDIT_FILL_KPI_REPORT_SUCCESS =
  'FillKpiReportForm/EDIT_FILL_KPI_REPORT_SUCCESS';
