export const LOAD_POWER_BY_RANGE_SUMMARY =
  'PowerByRangeSummary/LOAD_POWER_BY_RANGE_SUMMARY';
export const LOAD_POWER_BY_RANGE_SUMMARY_SUCCESS =
  'PowerByRangeSummary/LOAD_POWER_BY_RANGE_SUMMARY_SUCCESS';
export const LOAD_POWER_BY_RANGE_SUMMARY_ERROR =
  'PowerByRangeSummary/LOAD_POWER_BY_RANGE_SUMMARY_ERROR';
