export const LOAD_ALERT_CONFIGURATION_BY_ID =
  'AlertConfiguration/LOAD_ALERT_CONFIGURATION_BY_ID';
export const LOAD_ALERT_CONFIGURATION_BY_ID_ERROR =
  'AlertConfiguration/LOAD_ALERT_CONFIGURATION_BY_ID_ERROR';
export const LOAD_ALERT_CONFIGURATION_BY_ID_SUCCESS =
  'AlertConfiguration/LOAD_ALERT_CONFIGURATION_BY_ID_SUCCESS';
