export const REMOVE_ALERT_CONFIGURATION =
  'AlertConfigurationForm/REMOVE_ALERT_CONFIGURATION';
export const REMOVE_ALERT_CONFIGURATION_SUCCESS =
  'AlertConfigurationForm/REMOVE_ALERT_CONFIGURATION_SUCCESS';
export const REMOVE_ALERT_CONFIGURATION_ERROR =
  'AlertConfigurationForm/REMOVE_ALERT_CONFIGURATION_ERROR';

export const CREATE_ALERT_CONFIGURATION =
  'AlertConfigurationForm/CREATE_ALERT_CONFIGURATION';
export const CREATE_ALERT_CONFIGURATION_ERROR =
  'AlertConfigurationForm/CREATE_ALERT_CONFIGURATION_ERROR';
export const CREATE_ALERT_CONFIGURATION_SUCCESS =
  'AlertConfigurationForm/CREATE_ALERT_CONFIGURATION_SUCCESS';

export const EDIT_ALERT_CONFIGURATION =
  'AlertConfigurationForm/EDIT_ALERT_CONFIGURATION';
export const EDIT_ALERT_CONFIGURATION_ERROR =
  'AlertConfigurationForm/EDIT_ALERT_CONFIGURATION_ERROR';
export const EDIT_ALERT_CONFIGURATION_SUCCESS =
  'AlertConfigurationForm/EDIT_ALERT_CONFIGURATION_SUCCESS';
