export const REMOVE_CONSUMPTION_FARE =
  'ConsumptionFareForm/REMOVE_CONSUMPTION_FARE';
export const REMOVE_CONSUMPTION_FARE_SUCCESS =
  'ConsumptionFareForm/REMOVE_CONSUMPTION_FARE_SUCCESS';
export const REMOVE_CONSUMPTION_FARE_ERROR =
  'ConsumptionFareForm/REMOVE_CONSUMPTION_FARE_ERROR';

export const CREATE_CONSUMPTION_FARE =
  'ConsumptionFareForm/CREATE_CONSUMPTION_FARE';
export const CREATE_CONSUMPTION_FARE_ERROR =
  'ConsumptionFareForm/CREATE_CONSUMPTION_FARE_ERROR';
export const CREATE_CONSUMPTION_FARE_SUCCESS =
  'ConsumptionFareForm/CREATE_CONSUMPTION_FARE_SUCCESS';

export const EDIT_CONSUMPTION_FARE =
  'ConsumptionFareForm/EDIT_CONSUMPTION_FARE';
export const EDIT_CONSUMPTION_FARE_ERROR =
  'ConsumptionFareForm/EDIT_CONSUMPTION_FARE_ERROR';
export const EDIT_CONSUMPTION_FARE_SUCCESS =
  'ConsumptionFareForm/EDIT_CONSUMPTION_FARE_SUCCESS';
