export const LOAD_PERFORMANCE_CONFIGURATIONS =
  'PerformanceConfiguration/LOAD_PERFORMANCE_CONFIGURATIONS';
export const LOAD_PERFORMANCE_CONFIGURATIONS_SUCCESS =
  'PerformanceConfiguration/LOAD_PERFORMANCE_CONFIGURATIONS_SUCCESS';
export const LOAD_PERFORMANCE_CONFIGURATIONS_ERROR =
  'PerformanceConfiguration/LOAD_PERFORMANCE_CONFIGURATIONS_ERROR';

export const CONSUMPTION_TOTAL = 'CONSUMPTION_TOTAL';
export const CONSUMPTION_PRODUCTIVE_HOURS = 'CONSUMPTION_PRODUCTIVE_HOURS';
export const CONSUMPTION_NOT_PRODUCTIVE_HOURS =
  'CONSUMPTION_NOT_PRODUCTIVE_HOURS';
export const CONSUMPTION_OFF_PEAK = 'CONSUMPTION_OFF_PEAK';
export const CONSUMPTION_PEAK = 'CONSUMPTION_PEAK';

export const ONE_WEEK = 'ONE_WEEK';
export const ONE_MONTH = 'ONE_MONTH';
export const WEEKLY = 'Semanal';
export const MONTHLY = 'Mensal';
