export const LOAD_CURRENT_FARES_BY_BRANCH =
  'BranchFaresContainer/LOAD_CURRENT_FARES_BY_BRANCH';
export const LOAD_CURRENT_FARES_BY_BRANCH_SUCCESS =
  'BranchFaresContainer/LOAD_CURRENT_FARES_BY_BRANCH_SUCCESS';
export const LOAD_CURRENT_FARES_BY_BRANCH_ERROR =
  'BranchFaresContainer/LOAD_CURRENT_FARES_BY_BRANCH_ERROR';
