export const LOAD_CONSUMPTION_FARE_BY_ID =
  'ConsumptionFare/LOAD_CONSUMPTION_FARE_BY_ID';
export const LOAD_CONSUMPTION_FARE_BY_ID_ERROR =
  'ConsumptionFare/LOAD_CONSUMPTION_FARE_BY_ID_ERROR';
export const LOAD_CONSUMPTION_FARE_BY_ID_SUCCESS =
  'ConsumptionFare/LOAD_CONSUMPTION_FARE_BY_ID_SUCCESS';
