export const REMOVE_DEMAND_FARE = 'DemandFareForm/REMOVE_DEMAND_FARE';
export const REMOVE_DEMAND_FARE_SUCCESS =
  'DemandFareForm/REMOVE_DEMAND_FARE_SUCCESS';
export const REMOVE_DEMAND_FARE_ERROR =
  'DemandFareForm/REMOVE_DEMAND_FARE_ERROR';

export const CREATE_DEMAND_FARE = 'DemandFareForm/CREATE_DEMAND_FARE';
export const CREATE_DEMAND_FARE_ERROR =
  'DemandFareForm/CREATE_DEMAND_FARE_ERROR';
export const CREATE_DEMAND_FARE_SUCCESS =
  'DemandFareForm/CREATE_DEMAND_FARE_SUCCESS';

export const EDIT_DEMAND_FARE = 'DemandFareForm/EDIT_DEMAND_FARE';
export const EDIT_DEMAND_FARE_ERROR = 'DemandFareForm/EDIT_DEMAND_FARE_ERROR';
export const EDIT_DEMAND_FARE_SUCCESS =
  'DemandFareForm/EDIT_DEMAND_FARE_SUCCESS';
