export const LOAD_BRANCH_DISTRIBUTORS =
  'BranchDistributorContainer/LOAD_BRANCH_DISTRIBUTORS';
export const LOAD_BRANCH_DISTRIBUTORS_SUCCESS =
  'BranchDistributorContainer/LOAD_BRANCH_DISTRIBUTORS_SUCCESS';
export const LOAD_BRANCH_DISTRIBUTORS_ERROR =
  'BranchDistributorContainer/LOAD_BRANCH_DISTRIBUTORS_ERROR';

export const EDIT_BRANCH_DISTRIBUTORS =
  'BranchDistributorContainer/EDIT_BRANCH_DISTRIBUTORS';
export const EDIT_BRANCH_DISTRIBUTORS_SUCCESS =
  'BranchDistributorContainer/EDIT_BRANCH_DISTRIBUTORS_SUCCESS';
export const EDIT_BRANCH_DISTRIBUTORS_ERROR =
  'BranchDistributorContainer/EDIT_BRANCH_DISTRIBUTORS_ERROR';
