export const LOAD_PRODUCTIVE_HOURS =
  'App/ProductiveHoursPage/LOAD_PRODUCTIVE_HOURS';
export const LOAD_PRODUCTIVE_HOURS_SUCCESS =
  'App/ProductiveHoursPage/LOAD_PRODUCTIVE_HOURS_SUCCESS';
export const LOAD_PRODUCTIVE_HOURS_ERROR =
  'App/ProductiveHoursPage/LOAD_PRODUCTIVE_HOURS_ERROR';
export const PRODUCTIVE_HOURS_FARE_AND_WORKING_HOURS_ERRORS =
  'App/ProductiveHoursPage/PRODUCTIVE_HOURS_FARE_AND_WORKING_HOURS_ERRORS';
