export const LOAD_BRANCH_BY_ID = 'Branch/LOAD_BRANCH_BY_ID';
export const LOAD_BRANCH_BY_ID_ERROR = 'Branch/LOAD_BRANCH_BY_ID_ERROR';
export const LOAD_BRANCH_BY_ID_SUCCESS = 'Branch/LOAD_BRANCH_BY_ID_SUCCESS';
