export const LOAD_PAGINATED_INFO_OF_EGG_WORKING_HOURS =
  'EggWorkingHoursContainer/LOAD_PAGINATED_INFO_OF_EGG_WORKING_HOURS';
export const LOAD_TOTAL_WORKING_HOURS_OF_EGG_SUCCESS =
  'EggWorkingHoursContainer/LOAD_TOTAL_WORKING_HOURS_OF_EGG_SUCCESS';
export const LOAD_PAGINATED_INFO_OF_EGG_WORKING_HOURS_SUCCESS =
  'EggWorkingHoursContainer/LOAD_PAGINATED_INFO_OF_EGG_WORKING_HOURS_SUCCESS';
export const LOAD_PAGINATED_INFO_OF_EGG_WORKING_HOURS_ERROR =
  'EggWorkingHoursContainer/LOAD_PAGINATED_INFO_OF_EGG_WORKING_HOURS_ERROR';

export const TESTE = 'EggWorkingHoursContainer/TESTE';

export const DELETE_WORKING_HOURS =
  'EggWorkingHoursContainer/DELETE_WORKING_HOURS';
export const DELETE_WORKING_HOURS_SUCCESS =
  'EggWorkingHoursContainer/DELETE_WORKING_HOURS_SUCCESS';
export const DELETE_WORKING_HOURS_ERROR =
  'EggWorkingHoursContainer/DELETE_WORKING_HOURS_ERROR';
