export const LOAD_DEMAND_EXCEED_FARE_BY_ID =
  'DemandExceedFare/LOAD_DEMAND_EXCEED_FARE_BY_ID';
export const LOAD_DEMAND_EXCEED_FARE_BY_ID_ERROR =
  'DemandExceedFare/LOAD_DEMAND_EXCEED_FARE_BY_ID_ERROR';
export const LOAD_DEMAND_EXCEED_FARE_BY_ID_SUCCESS =
  'DemandExceedFare/LOAD_DEMAND_EXCEED_FARE_BY_ID_SUCCESS';
