export const LOAD_BRANCH_DETAILS = 'BranchDetailsPage/LOAD_BRANCH_DETAILS';
export const LOAD_BRANCH_DETAILS_SUCCESS =
  'BranchDetailsPage/LOAD_BRANCH_DETAILS_SUCCESS';
export const LOAD_BRANCH_DETAILS_ERROR =
  'BranchDetailsPage/LOAD_BRANCH_DETAILS_ERROR';

export const REMOVE_BRANCH_DETAILS = 'BranchDetailsPage/REMOVE_BRANCH_DETAILS';
export const REMOVE_BRANCH_DETAILS_SUCCESS =
  'BranchDetailsPage/REMOVE_BRANCH_DETAILS_SUCCESS';
export const REMOVE_BRANCH_DETAILS_ERROR =
  'BranchDetailsPage/REMOVE_BRANCH_DETAILS_ERROR';

export const CREATE_BRANCH_DETAILS = 'BranchDetailsPage/CREATE_BRANCH_DETAILS';
export const CREATE_BRANCH_DETAILS_ERROR =
  'BranchDetailsPage/CREATE_BRANCH_DETAILS_ERROR';
export const CREATE_BRANCH_DETAILS_SUCCESS =
  'BranchDetailsPage/CREATE_BRANCH_DETAILS_SUCCESS';

export const EDIT_BRANCH_DETAILS = 'BranchDetailsPage/EDIT_BRANCH_DETAILS';
export const EDIT_BRANCH_DETAILS_ERROR =
  'BranchDetailsPage/EDIT_BRANCH_DETAILS_ERROR';
export const EDIT_BRANCH_DETAILS_SUCCESS =
  'BranchDetailsPage/EDIT_BRANCH_DETAILS_SUCCESS';
