export const LOAD_APPORTIONMENTS = 'App/ApportionmentPage/LOAD_APPORTIONMENTS';
export const LOAD_APPORTIONMENTS_SUCCESS =
  'App/ApportionmentPage/LOAD_APPORTIONMENTS_SUCCESS';
export const LOAD_APPORTIONMENTS_ERROR =
  'App/ApportionmentPage/LOAD_APPORTIONMENTS_ERROR';
export const APPORTIONMENTS_FARE_AND_WORKING_HOURS_ERRORS =
  'App/ApportionmentPage/APPORTIONMENTS_FARE_AND_WORKING_HOURS_ERRORS';
