export const LOAD_ALERT_NOTIFICATIONS =
  'AlertNotification/LOAD_ALERT_NOTIFICATIONS';
export const LOAD_ALERT_NOTIFICATIONS_SUCCESS =
  'AlertNotification/LOAD_ALERT_NOTIFICATIONS_SUCCESS';
export const LOAD_ALERT_NOTIFICATIONS_ERROR =
  'AlertNotification/LOAD_ALERT_NOTIFICATIONS_ERROR';

export const STOP_LOAD_ALERT_NOTIFICATIONS =
  'AlertNotification/STOP_LOAD_ALERT_NOTIFICATIONS';
export const STOP_LOAD_ALERT_NOTIFICATIONS_SUCCESS =
  'AlertNotification/STOP_LOAD_ALERT_NOTIFICATIONS_SUCCESS';
