export const LOAD_AUTOCOMPLETE_BRANCHES =
  'AutocompleteBranches/LOAD_AUTOCOMPLETE_BRANCHES';
export const LOAD_AUTOCOMPLETE_BRANCHES_SUCCESS =
  'AutocompleteBranches/LOAD_AUTOCOMPLETE_BRANCHES_SUCCESS';
export const LOAD_AUTOCOMPLETE_BRANCHES_ERROR =
  'AutocompleteBranches/LOAD_AUTOCOMPLETE_BRANCHES_ERROR';
