export const REMOVE_COMPANY_INFO = 'CompanyInfoForm/REMOVE_COMPANY_INFO';
export const REMOVE_COMPANY_INFO_SUCCESS =
  'CompanyInfoForm/REMOVE_COMPANY_INFO_SUCCESS';
export const REMOVE_COMPANY_INFO_ERROR =
  'CompanyInfoForm/REMOVE_COMPANY_INFO_ERROR';

export const CREATE_COMPANY_INFO = 'CompanyInfoForm/CREATE_COMPANY_INFO';
export const CREATE_COMPANY_INFO_ERROR =
  'CompanyInfoForm/CREATE_COMPANY_INFO_ERROR';
export const CREATE_COMPANY_INFO_SUCCESS =
  'CompanyInfoForm/CREATE_COMPANY_INFO_SUCCESS';

export const EDIT_COMPANY_INFO = 'CompanyInfoForm/EDIT_COMPANY_INFO';
export const EDIT_COMPANY_INFO_ERROR =
  'CompanyInfoForm/EDIT_COMPANY_INFO_ERROR';
export const EDIT_COMPANY_INFO_SUCCESS =
  'CompanyInfoForm/EDIT_COMPANY_INFO_SUCCESS';
